webprofusion/certify

src/Forms/Controls/Details/CertificateDetails.cs
src/Management/VaultManager.cs

The "Renew" button on the Certificate Details control was not updating the UI after a successful renewal, and was not exporting the updated PFX on successful renewal, making it appear as though the "Auto Apply" function was not operational.
Before this change, Auto Apply would succeed if you click "Export" first (after a successful Renew). After this change, the Auto Apply button should work after a sucessful renew, and the UI is updated without having to click away and back to the certificate in the vault tree view.

Fix for #8 renew/auto-apply button

---

src/Properties/Resources.Designer.cs
src/Properties/Resources.resx

The web.config file that was used by default doesn't work with a lot of different sites because of the order of the extensionless URL handler and the Static file handler.  This update fixes the problem.

Updated the Web.Config template to operate with more websites.

---

src/Forms/MainForm.cs
src/Management/PowershellManager.cs

Was getting weird behavior when I tested this out in an environment that didn't have ACMESharp POSH module installed, but couldn't understand it -- it was because the POSH module wasn't installed.
This adds a test during app startup to make sure that it's there before continuing.

Ensure ACMESharp POSH module dependency is installed on startup

---

src/Certify.Windows.csproj
src/Management/IISManager.cs
src/Management/PowershellManager.cs
src/packages.config

I have a personal project with international domain name and I wanted to install LetsEncrypt cert on it using Certify.
The changes boiled down to two modifications (International Domain Name bindings in IIS are configured with non-ascii chars)
1. Certificate dns should be requested in ASCII
2. When installing certificate into IIS the bindings should be searched using Unicode variant of domain name
Successfully installed certificates on these domains:
https://grojaraštis.lt/ https://www.grojaraštis.lt/

Add support for International domain names

---

src/Management/IISManager.cs

Previous method was only removing the certificate from a certificate collection. The cert will now be removed from the store.

Fixed bug preventing cert deletion

---

src/Certify.Core/Management/VaultManager.cs
src/Certify.Winforms/Forms/Controls/CertRequestSettingsIIS.cs

Updated the ComputeIdentifierAlias method to check if the domain begins with a digit. If so, it will prepend the string "alias_" so that it is compliant with the ACMESharp specs. See webprofusion/Certify#38.
Fixed bug that caused a null reference exception if you call DeleteIdentifierByDNS after the vault is first initialized.
Fixed bug where CertRequestDialog wasn't closing after checks for extensionless content fail.

Prevent alias from beginning with a digit, fix bug causing null reference exception

---

src/Certify.CLI/Certify.CLI.csproj
src/Certify.CLI/Program.cs
src/Certify.CLI/packages.config
src/Certify.Core/Certify.Core.csproj
src/Certify.Core/Management/IISManager.cs
src/Certify.Core/Management/PowershellManager.cs
src/Certify.Core/packages.config
src/Certify.Winforms/Certify.Winforms.csproj
src/Certify.Winforms/Forms/Controls/CertRequestSettingsIIS.cs
src/Certify.Winforms/packages.config

So almost three months have passed since I submitted PR for IDNs and I had to renew certs but had to make some fixes for Certify to work.
Main theme of the changes is that when dealing with ACMESharp we should always use ASCII representation of IDN but when dealing with IIS we should use pretty (unicode) name.

Fix support for international domain names

---

src/Certify.CLI/App.config
src/Certify.Core/app.config
src/Certify.UI/App.config
src/Certify.Winforms/App.config

Certify is using Newtonsoft.Json v10 but binding redirects point to v9. If you do clean checkout and don't have a v9 in your packages folder you get an exception upon startup.

Fix Newtonsoft.Json binding redirects

---

src/Certify.Core/Management/IISManager.cs
src/Certify.UI/Controls/ManagedItemSettings.xaml
src/Certify.UI/Controls/ManagedItemSettings.xaml.cs
src/Certify.UI/Controls/ManagedSites.xaml

The cert auto-install wasn't working right in IIS7.5, it would create HTTPS bindings including the hostname which isn't supported (SNI is also not available). Changed the default behavior to auto create host- and sni-less bindings for IIS versions below 8.
A few small UI changes - the managed site title was white-on-white on Server 2008 R2's default color scheme, fixed that, and shortened some label text which was being overlapped by a checkbox.
Also cleared out the manual binding info being saved to `manageditems.json` if the user changed from manual back to auto-binding and saved, to avoid those values being used by `IISManager.InstallCertForRequest`.

Improved support for IIS7.5 (Server 2008 R2)

---

src/Certify.Core/Certify.Core.csproj
src/Certify.Core/Management/CertifyManager.cs
src/Certify.Core/Management/PowerShellManager.cs
src/Certify.Core/Models/CertRequestConfig.cs
src/Certify.Core/Models/CertificateRequestResult.cs
src/Certify.UI/Certify.UI.csproj
src/Certify.UI/Controls/ManagedItemSettings.xaml
src/Certify.UI/Controls/ManagedItemSettings.xaml.cs

I realized that RRAS's SSTP VPN (whew, that's a lot of acronyms) could use the SSL certificate installed in IIS by Certify to do VPN encryption, but it wouldn't automatically switch to the auto-renewed certificates until the service was restarted (at least in Windows Server 2008 R2). I figured that was a good use case for a request hook as talked about in webprofusion/certify#63. I added post- and pre-request hooks as well as the ability to modify the RequestConfig such as updating `ManagedItem.RequestConfig.WebsiteRootPath` as discussed in webprofusion/certify#146.
Also exposed the website root directory in the UI in case there is a special directory (like ASP.NET Core's convention for storing static files in wwwroot) that the challenge files should be based out of:
Example script: …

Add Powershell Hooks for Pre/Post Request Actions

---

src/Certify.Core/Management/CertifyManager.cs
src/Certify.Core/Management/IISManager.cs
src/Certify.Core/Models/CertRequestConfig.cs
src/Certify.UI/ViewModel/AppModel.cs

Allows omitting the Website Root Path from the `ManagedSite` configuration so that it can be determined at the time of certificate renewal instead.
- If the website root path is provided, it will be used during certificate renewal.
- If the path is not provided, then the current website root path is determined based on the IIS configuration for the matching IIS Site by Site Id.
This satisfies the deployment scenario in #146 by simply omitting the path while still supporting existing scenarios where it may be desirable to store and always use a particular path.
The default behavior when adding a new managed site configuration has changed to what I feel is the more common scenario (omitting the path).  If desired, the user can still set it in the UI / config file.
It wasn't clear how best …

Determine current website root path during certificate renewal

---

src/Certify.Core/Management/APIProviders/ACMESharpProvider.cs
src/Certify.Core/Management/APIProviders/CertesProvider.cs
src/Certify.Core/Management/CertifyManager.cs
src/Certify.Core/Management/IISManager.cs
src/Certify.Core/Management/IVaultProvider.cs
src/Certify.Core/Management/VaultManager.cs
src/Certify.Core/Models/CertRequestConfig.cs

I haven't had a chance to fully test this but wanted to let @mpetito and @webprofusion-chrisc see what I was talking about for the change to PR #149. This would allow the current pre-PR #149 behavior to remain the same, but would introduce the ability for the user to change the WebsiteRootPath in the UI to something like `%websiteroot%` or `%websiteroot%\wwwroot`, and that value would be expanded to the appropriate current value of configured IIS site physical path at the time of the certificate request. This has the added benefit of being able to auto-update the path when using ASP.NET Core MVC (or any other framework that uses a non-root path for hosting static files like "wwwroot" or "Content" or "Public"). 
This change also removes the `CertRequestConfig` cloning code so that the …

Modify website root updating

---

src/Certify.UI/Controls/ManagedSites.xaml
src/Certify.UI/Controls/ManagedSites.xaml.cs

Added text search filtering for managed site name and domain name:
Addresses issue #101.

add managed site list filtering

---

src/Certify.Core/Management/VaultManager.cs
src/Certify.UI/Controls/ManagedItemSettings.xaml.cs
src/Certify.UI/ViewModel/AppModel.cs

Cleans up the access to PrimaryDomain and GroupId (re: https://github.com/webprofusion/certify/pull/164#issuecomment-333430638)
Tests all domains when running a simulated challenge response (re: https://github.com/webprofusion/certify/pull/164#issuecomment-333519010) - fixes #165

Test all domains, centralize settings model updating

---

src/Certify.UI/Certify.UI.csproj
src/Certify.UI/Controls/ManagedItemSettings.xaml
src/Certify.UI/Controls/ManagedItemSettings.xaml.cs
src/Certify.UI/Controls/ManagedSites.xaml
src/Certify.UI/Controls/ManagedSites.xaml.cs
src/Certify.UI/Controls/Settings.xaml
src/Certify.UI/MainWindow.xaml
src/Certify.UI/ViewModel/AppModel.cs
src/Certify.UI/ViewModel/DesignViewModel.cs

Fixed #167 (domain options list wasn't expanding), in the process created mocked view model for the designer so changes can be previewed in Visual Studio (you might need to click the "enable project code" button on the designer to see it): 
Also fixed a bug where a managed site could be saved without primary domain if "Include" was unchecked, updated text on the options tab to include reference to port 443 for TLS-SNI, changed some margins around and prevented tab reordering.

UI Updates

---

src/Certify.Core/Certify.Core.csproj
src/Certify.Core/Management/NetworkUtils.cs
src/Certify.Core/Management/VaultManager.cs
src/Certify.Core/packages.config
src/Certify.Tests/Certify.Core.Tests.Unit/Certify.Core.Tests.Unit.csproj
src/Certify.Tests/Certify.Core.Tests.Unit/DnsTests.cs
src/Certify.Tests/Certify.Core.Tests.Unit/app.config
src/Certify.Tests/Certify.Core.Tests.Unit/packages.config

* Pulled out network code (CheckUrl, CheckSNI) from VaultManager into NetworkUtils class
* Added CheckDNS to NetworkUtils to verify DNS lookups, CAA and DNSSEC 
* Added test to UnitTest project
* Fixes #171 
Note: DNSSEC checks are slow, on the order of a second per domain name being checked. This could have an impact for configurations with large numbers of domains. ~~This could be mitigated by performing the checks in parallel.~~ Done

DNS Features

---

.gitmodules
src/Certify.Core/ACMESharpCompat/ACMESharpUtils.cs
src/Certify.Core/ACMESharpCompat/Helpers.cs
src/Certify.Core/Management/APIProviders/ACMESharpProvider.cs
src/Certify.Core/Management/APIProviders/CertesProvider.cs
src/Certify.Core/Management/CertifyManager.cs
src/Certify.Core/Management/IVaultProvider.cs
src/Certify.Core/Management/VaultManager.cs
src/Certify.Core/Models/ManagedItem.cs
src/Certify.UI/Controls/ManagedItemSettings.xaml
src/Certify.UI/Controls/ManagedItemSettings.xaml.cs
src/Certify.UI/ViewModel/AppModel.cs

* Switched ACMESharp submodule to marcus-l/acmesharp certify branch (includes the TLS-SNI and revocation PRs). The PR to support revoke-cert is https://github.com/ebekker/ACMESharp/pull/301
* Update to Certify Core and UI
(made the button red and added a confirm step to avoid mistakes)

Certificate Revocation support

---

src/Certify.Core/Management/NetworkUtils.cs
src/Certify.Tests/Certify.Core.Tests.Unit/DnsTests.cs

* Added test for "cloudapp.net" to the Unit Tests (not caught by existing tests because it was a _valid domain_, but did not resolve to an IP address)
* Fixes #184

 Fix for error for valid domain that does not resolve

---

.gitmodules
src/Certify.Core/ACMESharpCompat/Helpers.cs

My TLS-SNI, Useragent/Language and Revoke PRs were been merged into ACMESharp, so this switches the submodule back to the main project head at https://github.com/ebekker/ACMESharp/commit/3cb30fedb2d597415916b3f1ac9f447816c2e36a

 Switch submodule back to main ACMESharp repo

---

src/Certify.Core/Management/CertifyManager.cs
src/Certify.Core/Management/ItemManager.cs
src/Certify.Core/Models/ManagedItem.cs
src/Certify.Core/Models/VaultItem.cs
src/Certify.UI/Controls/ManagedItemSettings.xaml
src/Certify.UI/Controls/ManagedItemSettings.xaml.cs
src/Certify.UI/Controls/ManagedSites.xaml
src/Certify.UI/Controls/ManagedSites.xaml.cs
src/Certify.UI/Controls/Settings.xaml.cs
src/Certify.UI/MainWindow.xaml
src/Certify.UI/MainWindow.xaml.cs
src/Certify.UI/Resources/SR.Designer.cs
src/Certify.UI/Resources/SR.resx
src/Certify.UI/Resources/SR.zh-Hans.resx
src/Certify.UI/Utils/BooleanConverters.cs
src/Certify.UI/ViewModel/AppModel.cs
src/Certify.UI/ViewModel/DesignViewModel.cs
src/Certify.UI/Windows/ImportManagedSites.xaml.cs

* Misc UI updates
* Keyboard shortcuts (CTRL-F, DEL) on site list
* Better "discard changes?" detection and handling
* Fix colors on Server 2008 R2 (or computers with Aero turned off)
* Made the DesignViewModel usable for testing (uncomment the "new DesignViewModel()" line in AppModel.cs)
* Fix bug where site list filter stopped working after any settings save
* Core update
* Centralize change detection on BindableBase objects, automatically bubble up and down IsChanged
I apologize for the size of the PR, but most of the changes (aside from the color fixes) are linked together pretty tightly. I did try to group the changes together into logical commits so they'd be digestable in smaller chunks. 
I'd be a little more careful than usual merging this in without testing, honestly the keyboard …

UI Fixes and new features plus refactoring

---

src/Certify.Core/Certify.Core.csproj
src/Certify.Core/Management/ItemManager.cs
src/Certify.Core/Management/Util.cs
src/Certify.Core/Models/BindableBase.cs
src/Certify.Core/Models/ManagedItem.cs
src/Certify.Core/packages.config
src/Certify.Tests/Certify.Core.Tests.Unit/Certify.Core.Tests.Unit.csproj
src/Certify.Tests/Certify.Core.Tests.Unit/ManagedSiteTests.cs
src/Certify.Tests/Certify.Core.Tests.Unit/packages.config
src/Certify.UI/Certify.UI.csproj
src/Certify.UI/Controls/ManagedItemSettings.xaml.cs
src/Certify.UI/Controls/ManagedSites.xaml
src/Certify.UI/ViewModel/AppModel.cs
src/Certify.UI/packages.config

Optimized ItemManager for large numbers of sites, changed test back to 100K sites. I think test is actually more stressful than the UI due to the way it loads the sites one by one rather than in bulk. I was able to load the test settings file from #177 in the UI pretty quickly and navigate around without any UI delay with this optimization.

Better handling for large number of sites

---

src/Certify.Core/Certify.Core.csproj
src/Certify.Core/Management/CertificateManager.cs
src/Certify.Core/Utils/X509ExtensionUtilities.cs

I noticed that my site using tls-sni-01 challenge started failing with the most recent code (Slack webhook notifications FTW!). After some debugging I came to the unexpected conclusion that there was a bug in the BouncyCastle library code, which it ends up has been fixed in the source (https://github.com/bcgit/bc-csharp/commit/96e500fd17aac287d0682aaf58c7f1f4341e1fd6) but has not been incorporated into a release yet. 
I have no idea why this was working before, none of the related code on our side has changed. Not sure if my test environment changed somehow (Windows Update?) or there was some other upstream change, since if it was failing on parsing the certificate SAN for verification, it should never have worked. Anyway, this fixes the problem so my domain validation works again.
I got …

Fix TLS-SNI local testing

---

src/Certify.CLI/Program.cs

- added optional column headers that can be used in no particular order
- added powershell and webhook options
- changed all hardcoded RequestConfig options to be able to be passed into csv
- added duplicate checking to prevent same SAN from being used in multiple certs (Wasn't sure how you wanted this setup. Figured wasn't much point to having multiple certs w/ same SAN). Checks what's being imported as well as what's already in the system
- Added some error handling to prevent 1 bad row from stopping the entire import

Enhancements to csvImport script

---

docs/Request Script Hooks.md

There was a hidden bonus 'g' in ManagedItem example.

Fixed typo: MangagedItem to ManagedItem

---

src/Certify.Providers/DNS/Azure/DnsProviderAzure.cs

Azure DNS Provider was not appending to the TXT record, when wildcard + non-wildcard domain is created.
Issue: #363

Fix Azure DNS Provider to support wildcard and the same non-wildcard domain

---

src/Certify.UI/Certify.UI.csproj
src/Certify.UI/MainWindow.xaml.cs
src/Certify.UI/Settings/UISettings.cs

Added support for saving the Certify app window width, height and position when closing the main app window. The settings are stored in a file called ui.json in the program data directory, and the settings are read when the app window is loaded to restore the previous session window size and position.

added support for saving and restoring UI app window size and position

---

Certify.sln
src/Certify.Core/Certify.Core.csproj
src/Certify.Core/Management/Challenges/ChallengeProviders.cs
src/Certify.Providers/DNS/NameCheap/DnsProviderNameCheap.cs
src/Certify.Providers/DNS/NameCheap/NameCheap.csproj
src/Certify.Providers/DNS/NameCheap/NameCheapHostRecord.cs
src/Certify.Providers/DNS/NameCheap/XmlExtensions.cs

Closes #376.
Tricky things to know about NameCheap API:
* API is only available if you have $50 on your account or have bought $50 worth of services in the last 2 years
* The "API activation takes up to 2 business days" claim is baloney, they can do it immediately if you contact support and will likely ignore your request altogether if you don't.
* You need to manually add your server's IP to a whitelist before you can send API requests. If you have a dynamic IP, well, oops, you're out of luck.
* The API _also_ requires sending current client IP with every single request (hence the "IP" field in NameCheap credentials).
I didn't add anything to the documentation project yet. Can open another pull request there if required.

NameCheap DNS provider
